# Generated by Django 5.2 on 2025-07-19 08:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracker', '0005_maintenancecategory_vehicle_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('stocks', 'Stocks'), ('bonds', 'Bonds'), ('mutual_funds', 'Mutual Funds'), ('etf', 'ETF'), ('retirement_401k', '401(k)'), ('retirement_ira', 'IRA'), ('retirement_roth', 'Roth IRA'), ('savings', 'Savings Account'), ('cd', 'Certificate of Deposit'), ('real_estate', 'Real Estate'), ('crypto', 'Cryptocurrency'), ('other', 'Other')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('mortgage', 'Mortgage'), ('auto', 'Auto Loan'), ('personal', 'Personal Loan'), ('heloc', 'HELOC'), ('student', 'Student Loan'), ('credit_card', 'Credit Card'), ('business', 'Business Loan'), ('other', 'Other')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for the investment', max_length=200)),
                ('institution', models.CharField(blank=True, max_length=200, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('initial_amount', models.DecimalField(decimal_places=2, help_text='Initial investment amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('current_value', models.DecimalField(decimal_places=2, help_text='Current market value', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Target investment goal', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('annual_return_rate', models.DecimalField(decimal_places=4, help_text='Expected annual return rate as decimal (e.g., 7.5 for 7.5%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('-99.9999')), django.core.validators.MaxValueValidator(Decimal('99.9999'))])),
                ('compounding_frequency', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually'), ('continuous', 'Continuous')], default='monthly', max_length=20)),
                ('monthly_contribution', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Regular monthly contribution amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('start_date', models.DateField(help_text='Investment start date')),
                ('maturity_date', models.DateField(blank=True, help_text='Investment maturity date (if applicable)', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('matured', 'Matured'), ('transferred', 'Transferred')], default='active', max_length=20)),
                ('is_tax_advantaged', models.BooleanField(default=False, help_text='401k, IRA, etc.')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_investments', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='tracker.family')),
                ('investment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments', to='loans.investmenttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for the loan', max_length=200)),
                ('lender', models.CharField(blank=True, max_length=200, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('principal_amount', models.DecimalField(decimal_places=2, help_text='Original loan amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('current_balance', models.DecimalField(decimal_places=2, help_text='Current outstanding balance', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('interest_rate', models.DecimalField(decimal_places=4, help_text='Annual interest rate as decimal (e.g., 5.25 for 5.25%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0000')), django.core.validators.MaxValueValidator(Decimal('99.9999'))])),
                ('term_months', models.PositiveIntegerField(help_text='Original loan term in months')),
                ('monthly_payment', models.DecimalField(decimal_places=2, help_text='Scheduled monthly payment amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('bi_weekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='monthly', max_length=20)),
                ('start_date', models.DateField(help_text='Loan origination date')),
                ('first_payment_date', models.DateField(help_text='Date of first payment')),
                ('maturity_date', models.DateField(help_text='Scheduled payoff date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paid_off', 'Paid Off'), ('refinanced', 'Refinanced'), ('default', 'Default')], default='active', max_length=20)),
                ('is_variable_rate', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_loans', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='tracker.family')),
                ('loan_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='loans.loantype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('principal_amount', models.DecimalField(decimal_places=2, help_text='Amount applied to principal', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('interest_amount', models.DecimalField(decimal_places=2, help_text='Amount applied to interest', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('escrow_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount for escrow (taxes, insurance)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_type', models.CharField(choices=[('scheduled', 'Scheduled Payment'), ('extra_principal', 'Extra Principal'), ('extra_payment', 'Extra Payment'), ('lump_sum', 'Lump Sum')], default='scheduled', max_length=20)),
                ('balance_after_payment', models.DecimalField(decimal_places=2, help_text='Remaining balance after this payment', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_payments', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='loans.loan')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Refinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refinance_date', models.DateField()),
                ('closing_costs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cash_out_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cash taken out during refinance', max_digits=10)),
                ('original_balance_at_refinance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_payments_on_original', models.DecimalField(decimal_places=2, help_text='Total amount paid on original loan', max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('new_loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refinances_as_new', to='loans.loan')),
                ('original_loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refinances_as_original', to='loans.loan')),
            ],
            options={
                'ordering': ['-refinance_date'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('scheduled_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('escrow_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('beginning_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ending_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actual_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.payment')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_payments', to='loans.loan')),
            ],
            options={
                'ordering': ['payment_number'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit/Contribution'), ('withdrawal', 'Withdrawal'), ('dividend', 'Dividend/Interest'), ('fee', 'Fee'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('value_adjustment', 'Market Value Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('shares', models.DecimalField(blank=True, decimal_places=6, help_text='Number of shares (if applicable)', max_digits=15, null=True)),
                ('price_per_share', models.DecimalField(blank=True, decimal_places=4, help_text='Price per share at transaction', max_digits=10, null=True)),
                ('balance_after_transaction', models.DecimalField(decimal_places=2, help_text='Investment value after this transaction', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_investment_transactions', to=settings.AUTH_USER_MODEL)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loans.investment')),
            ],
            options={
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['investment', 'transaction_date'], name='loans_inves_investm_00a30b_idx'), models.Index(fields=['transaction_type'], name='loans_inves_transac_faec30_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['family', 'status'], name='loans_inves_family__8df077_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['investment_type', 'status'], name='loans_inves_investm_447e70_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['created_by', 'status'], name='loans_inves_created_0cc0ea_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['family', 'status'], name='loans_loan_family__c76e4a_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['loan_type', 'status'], name='loans_loan_loan_ty_13c084_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['created_by', 'status'], name='loans_loan_created_c147e7_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['loan', 'payment_date'], name='loans_payme_loan_id_50546c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_type'], name='loans_payme_payment_1266b2_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledpayment',
            index=models.Index(fields=['loan', 'payment_number'], name='loans_sched_loan_id_5eca2e_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledpayment',
            index=models.Index(fields=['due_date'], name='loans_sched_due_dat_2b8dca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scheduledpayment',
            unique_together={('loan', 'payment_number')},
        ),
    ]
