# Generated by Django 5.2 on 2025-07-19 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='is_shared',
            field=models.BooleanField(default=True, help_text='Whether this investment is shared with all family members or private to creator'),
        ),
        migrations.AddField(
            model_name='investment',
            name='read_only_users',
            field=models.ManyToManyField(blank=True, help_text='Users who can view but not edit this investment', related_name='readonly_investments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investment',
            name='shared_with',
            field=models.ManyToManyField(blank=True, help_text='Specific users this investment is shared with (in addition to family members)', related_name='shared_investments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='is_shared',
            field=models.BooleanField(default=True, help_text='Whether this loan is shared with all family members or private to creator'),
        ),
        migrations.AddField(
            model_name='loan',
            name='read_only_users',
            field=models.ManyToManyField(blank=True, help_text='Users who can view but not edit this loan', related_name='readonly_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='shared_with',
            field=models.ManyToManyField(blank=True, help_text='Specific users this loan is shared with (in addition to family members)', related_name='shared_loans', to=settings.AUTH_USER_MODEL),
        ),
    ]
