# Generated by Django 5.2 on 2025-07-19 19:18

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_investment_is_shared_investment_read_only_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='payment_type',
            field=models.CharField(choices=[('automatic', 'Automatic Payments'), ('manual', 'Manual Payments')], default='automatic', help_text='Whether payments are automatic/scheduled or manual/sporadic', max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='monthly_payment',
            field=models.DecimalField(decimal_places=2, help_text='Scheduled monthly payment amount (for automatic) or minimum payment (for manual)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
