# Generated by Django 5.2 on 2025-06-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_location_family_alter_location_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gallonsperhour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
