# Generated by Django 5.2 on 2025-07-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_add_gallonsperhour_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancecategory',
            name='vehicle_types',
            field=models.JSONField(default=list, help_text='List of vehicle types this category applies to'),
        ),
    ]
