# Generated by Django 5.2 on 2025-10-06 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_maintenancecategory_vehicle_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Additional details about this specific item', null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(limit_choices_to={'event_type': 'maintenance'}, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_items', to='tracker.event')),
                ('maintenance_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.maintenancecategory')),
            ],
            options={
                'indexes': [models.Index(fields=['event', 'maintenance_category'], name='tracker_mai_event_i_8843ef_idx'), models.Index(fields=['maintenance_category'], name='tracker_mai_mainten_a21cc1_idx')],
            },
        ),
    ]
