# Generated by Django 5.2 on 2025-10-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_maintenanceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='boat_engine_type',
            field=models.CharField(blank=True, choices=[('inboard', 'Inboard'), ('outboard', 'Outboard'), ('io', 'Inboard/Outboard (I/O)')], help_text='Engine type for boats', max_length=20, null=True),
        ),
    ]
