# Generated by Django 5.2 on 2025-10-06 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_vehicle_boat_engine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancecategory',
            name='boat_engine_types',
            field=models.JSONField(blank=True, default=list, help_text='List of boat engine types this category applies to (only for boat maintenance)'),
        ),
    ]
